# Generated by Django 3.1 on 2020-08-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
