# Generated by Django 3.1 on 2020-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('activitiesCompleted', models.TextField(verbose_name='Activities Completed')),
                ('activitiesInProgress', models.TextField(null=True, verbose_name='Activities In Progress')),
                ('activitiesNextWeek', models.TextField(null=True, verbose_name='Activities Next Week')),
                ('issues', models.TextField(null=True, verbose_name='Activities Next Week')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
